//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR.WizPlant.Integrate.Csgii.SBTZSOA {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://soa.csg.cn", ConfigurationName="SBTZSOA.SOAServicePort")]
    public interface SOAServicePort {
        
        // CODEGEN: 操作 queryDeviceInfoById 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PR.WizPlant.Integrate.Csgii.SBTZSOA.queryDeviceInfoByIdResponse1 queryDeviceInfoById(PR.WizPlant.Integrate.Csgii.SBTZSOA.queryDeviceInfoByIdRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult BeginqueryDeviceInfoById(PR.WizPlant.Integrate.Csgii.SBTZSOA.queryDeviceInfoByIdRequest1 request, System.AsyncCallback callback, object asyncState);
        
        PR.WizPlant.Integrate.Csgii.SBTZSOA.queryDeviceInfoByIdResponse1 EndqueryDeviceInfoById(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.csg.cn")]
    public partial class QueryDeviceInfoByIdRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string deviceIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string deviceId {
            get {
                return this.deviceIdField;
            }
            set {
                this.deviceIdField = value;
                this.RaisePropertyChanged("deviceId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.csg.cn")]
    public partial class LstTechParamItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string classifyIdField;
        
        private string classifyNameField;
        
        private string techParamIdField;
        
        private string columnNameField;
        
        private string techParamNameField;
        
        private string techParamValueField;
        
        private string unitsField;
        
        private string isMandatoryField;
        
        private string isShowField;
        
        private string sortNoField;
        
        private int dataTypeField;
        
        private bool dataTypeFieldSpecified;
        
        private string isVendorFillField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string classifyId {
            get {
                return this.classifyIdField;
            }
            set {
                this.classifyIdField = value;
                this.RaisePropertyChanged("classifyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string classifyName {
            get {
                return this.classifyNameField;
            }
            set {
                this.classifyNameField = value;
                this.RaisePropertyChanged("classifyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string techParamId {
            get {
                return this.techParamIdField;
            }
            set {
                this.techParamIdField = value;
                this.RaisePropertyChanged("techParamId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string columnName {
            get {
                return this.columnNameField;
            }
            set {
                this.columnNameField = value;
                this.RaisePropertyChanged("columnName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string techParamName {
            get {
                return this.techParamNameField;
            }
            set {
                this.techParamNameField = value;
                this.RaisePropertyChanged("techParamName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string techParamValue {
            get {
                return this.techParamValueField;
            }
            set {
                this.techParamValueField = value;
                this.RaisePropertyChanged("techParamValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string units {
            get {
                return this.unitsField;
            }
            set {
                this.unitsField = value;
                this.RaisePropertyChanged("units");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=7)]
        public string isMandatory {
            get {
                return this.isMandatoryField;
            }
            set {
                this.isMandatoryField = value;
                this.RaisePropertyChanged("isMandatory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=8)]
        public string isShow {
            get {
                return this.isShowField;
            }
            set {
                this.isShowField = value;
                this.RaisePropertyChanged("isShow");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=9)]
        public string sortNo {
            get {
                return this.sortNoField;
            }
            set {
                this.sortNoField = value;
                this.RaisePropertyChanged("sortNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int dataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
                this.RaisePropertyChanged("dataType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataTypeSpecified {
            get {
                return this.dataTypeFieldSpecified;
            }
            set {
                this.dataTypeFieldSpecified = value;
                this.RaisePropertyChanged("dataTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=11)]
        public string isVendorFill {
            get {
                return this.isVendorFillField;
            }
            set {
                this.isVendorFillField = value;
                this.RaisePropertyChanged("isVendorFill");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.csg.cn")]
    public partial class DeviceGisDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string deviceCodeField;
        
        private string deviceNameField;
        
        private string classifyIdField;
        
        private string classifyNameField;
        
        private string isCapitalAssetsField;
        
        private string isCapitalAssetsStrField;
        
        private string proprietorCompanyOnameField;
        
        private string proprietorCompanyOidField;
        
        private string baseVoltageIdField;
        
        private string baseVoltageNameField;
        
        private string voltagePageShowField;
        
        private string isVirtualDeviceField;
        
        private string isVirtualDeviceStrField;
        
        private string measurementUnitField;
        
        private string amountField;
        
        private string manufacturerField;
        
        private string manufacturerIdField;
        
        private string latestManufacturerField;
        
        private string vendorField;
        
        private string vendorIdField;
        
        private string deviceModelField;
        
        private string leaveFactoryNoField;
        
        private string leaveFactoryDateStrField;
        
        private string warrantyPeriodField;
        
        private string plantTransferDateStrField;
        
        private string assetStateField;
        
        private string assetStateStrField;
        
        private string statusDateStrField;
        
        private string runningCodeField;
        
        private double latitudeField;
        
        private bool latitudeFieldSpecified;
        
        private double longitudeField;
        
        private bool longitudeFieldSpecified;
        
        private string latitudeStrField;
        
        private string longitudeStrField;
        
        private string altitudeField;
        
        private string topographyField;
        
        private string topographyStrField;
        
        private string bureauUnitsOidField;
        
        private string bureauUnitsOnameField;
        
        private string dispatchLevelField;
        
        private string dispatchLevelStrField;
        
        private string runmanageOidField;
        
        private string runmanageONameField;
        
        private string vindicateOidField;
        
        private string vindicateONameField;
        
        private string placeCodeField;
        
        private string flNameField;
        
        private string flCodeField;
        
        private string installCodeField;
        
        private string remarkField;
        
        private string powerGridFlagField;
        
        private string powerGridFlagStrField;
        
        private string ownerStationOidField;
        
        private string ownerStationONameField;
        
        private string countyCodeField;
        
        private string oldClassifyFullPathField;
        
        private string oldAliasNameField;
        
        private string isLabelField;
        
        private string isLabelStrField;
        
        private string isAssamblyField;
        
        private string isAssamblyStrField;
        
        private string isShareDeviceField;
        
        private string isShareDeviceStrField;
        
        private string dataSourceField;
        
        private string licensePlateNumberField;
        
        private string vindicatorUnitOnameField;
        
        private string vindicatorUnitOidField;
        
        private string capitalAssetsCodeField;
        
        private string installationLocationField;
        
        private string proprietorOwnerField;
        
        private string proprietorOwnerStrField;
        
        private string useLifeField;
        
        private string deviceModelIdField;
        
        private string deviceIdField;
        
        private string retireDateStrField;
        
        private string functionLocationIdField;
        
        private string classifyCodeField;
        
        private string classifyFullPathField;
        
        private string nominalVoltageField;
        
        private string parentFLIdField;
        
        private string parentFLNameField;
        
        private string bayIdField;
        
        private string bayNameField;
        
        private string siteIdField;
        
        private string siteNameField;
        
        private string bureauNameField;
        
        private string fullPathField;
        
        private string centerSubstationIdField;
        
        private string centerSubstationNameField;
        
        private string subsIdOfDisDeviceField;
        
        private string subsNameOfDisDeviceField;
        
        private string inventoryTaskNoField;
        
        private string assetDeviceIdField;
        
        private LstTechParamItem[] lstTechParamListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string deviceCode {
            get {
                return this.deviceCodeField;
            }
            set {
                this.deviceCodeField = value;
                this.RaisePropertyChanged("deviceCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string deviceName {
            get {
                return this.deviceNameField;
            }
            set {
                this.deviceNameField = value;
                this.RaisePropertyChanged("deviceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string classifyId {
            get {
                return this.classifyIdField;
            }
            set {
                this.classifyIdField = value;
                this.RaisePropertyChanged("classifyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string classifyName {
            get {
                return this.classifyNameField;
            }
            set {
                this.classifyNameField = value;
                this.RaisePropertyChanged("classifyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=4)]
        public string isCapitalAssets {
            get {
                return this.isCapitalAssetsField;
            }
            set {
                this.isCapitalAssetsField = value;
                this.RaisePropertyChanged("isCapitalAssets");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string isCapitalAssetsStr {
            get {
                return this.isCapitalAssetsStrField;
            }
            set {
                this.isCapitalAssetsStrField = value;
                this.RaisePropertyChanged("isCapitalAssetsStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string proprietorCompanyOname {
            get {
                return this.proprietorCompanyOnameField;
            }
            set {
                this.proprietorCompanyOnameField = value;
                this.RaisePropertyChanged("proprietorCompanyOname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string proprietorCompanyOid {
            get {
                return this.proprietorCompanyOidField;
            }
            set {
                this.proprietorCompanyOidField = value;
                this.RaisePropertyChanged("proprietorCompanyOid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string baseVoltageId {
            get {
                return this.baseVoltageIdField;
            }
            set {
                this.baseVoltageIdField = value;
                this.RaisePropertyChanged("baseVoltageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string baseVoltageName {
            get {
                return this.baseVoltageNameField;
            }
            set {
                this.baseVoltageNameField = value;
                this.RaisePropertyChanged("baseVoltageName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string voltagePageShow {
            get {
                return this.voltagePageShowField;
            }
            set {
                this.voltagePageShowField = value;
                this.RaisePropertyChanged("voltagePageShow");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=11)]
        public string isVirtualDevice {
            get {
                return this.isVirtualDeviceField;
            }
            set {
                this.isVirtualDeviceField = value;
                this.RaisePropertyChanged("isVirtualDevice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string isVirtualDeviceStr {
            get {
                return this.isVirtualDeviceStrField;
            }
            set {
                this.isVirtualDeviceStrField = value;
                this.RaisePropertyChanged("isVirtualDeviceStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string measurementUnit {
            get {
                return this.measurementUnitField;
            }
            set {
                this.measurementUnitField = value;
                this.RaisePropertyChanged("measurementUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=14)]
        public string amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string manufacturer {
            get {
                return this.manufacturerField;
            }
            set {
                this.manufacturerField = value;
                this.RaisePropertyChanged("manufacturer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string manufacturerId {
            get {
                return this.manufacturerIdField;
            }
            set {
                this.manufacturerIdField = value;
                this.RaisePropertyChanged("manufacturerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string latestManufacturer {
            get {
                return this.latestManufacturerField;
            }
            set {
                this.latestManufacturerField = value;
                this.RaisePropertyChanged("latestManufacturer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string vendor {
            get {
                return this.vendorField;
            }
            set {
                this.vendorField = value;
                this.RaisePropertyChanged("vendor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string vendorId {
            get {
                return this.vendorIdField;
            }
            set {
                this.vendorIdField = value;
                this.RaisePropertyChanged("vendorId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string deviceModel {
            get {
                return this.deviceModelField;
            }
            set {
                this.deviceModelField = value;
                this.RaisePropertyChanged("deviceModel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string leaveFactoryNo {
            get {
                return this.leaveFactoryNoField;
            }
            set {
                this.leaveFactoryNoField = value;
                this.RaisePropertyChanged("leaveFactoryNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string leaveFactoryDateStr {
            get {
                return this.leaveFactoryDateStrField;
            }
            set {
                this.leaveFactoryDateStrField = value;
                this.RaisePropertyChanged("leaveFactoryDateStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=23)]
        public string warrantyPeriod {
            get {
                return this.warrantyPeriodField;
            }
            set {
                this.warrantyPeriodField = value;
                this.RaisePropertyChanged("warrantyPeriod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string plantTransferDateStr {
            get {
                return this.plantTransferDateStrField;
            }
            set {
                this.plantTransferDateStrField = value;
                this.RaisePropertyChanged("plantTransferDateStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=25)]
        public string assetState {
            get {
                return this.assetStateField;
            }
            set {
                this.assetStateField = value;
                this.RaisePropertyChanged("assetState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string assetStateStr {
            get {
                return this.assetStateStrField;
            }
            set {
                this.assetStateStrField = value;
                this.RaisePropertyChanged("assetStateStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string statusDateStr {
            get {
                return this.statusDateStrField;
            }
            set {
                this.statusDateStrField = value;
                this.RaisePropertyChanged("statusDateStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string runningCode {
            get {
                return this.runningCodeField;
            }
            set {
                this.runningCodeField = value;
                this.RaisePropertyChanged("runningCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public double latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool latitudeSpecified {
            get {
                return this.latitudeFieldSpecified;
            }
            set {
                this.latitudeFieldSpecified = value;
                this.RaisePropertyChanged("latitudeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public double longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool longitudeSpecified {
            get {
                return this.longitudeFieldSpecified;
            }
            set {
                this.longitudeFieldSpecified = value;
                this.RaisePropertyChanged("longitudeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string latitudeStr {
            get {
                return this.latitudeStrField;
            }
            set {
                this.latitudeStrField = value;
                this.RaisePropertyChanged("latitudeStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string longitudeStr {
            get {
                return this.longitudeStrField;
            }
            set {
                this.longitudeStrField = value;
                this.RaisePropertyChanged("longitudeStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=33)]
        public string altitude {
            get {
                return this.altitudeField;
            }
            set {
                this.altitudeField = value;
                this.RaisePropertyChanged("altitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=34)]
        public string topography {
            get {
                return this.topographyField;
            }
            set {
                this.topographyField = value;
                this.RaisePropertyChanged("topography");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string topographyStr {
            get {
                return this.topographyStrField;
            }
            set {
                this.topographyStrField = value;
                this.RaisePropertyChanged("topographyStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string bureauUnitsOid {
            get {
                return this.bureauUnitsOidField;
            }
            set {
                this.bureauUnitsOidField = value;
                this.RaisePropertyChanged("bureauUnitsOid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string bureauUnitsOname {
            get {
                return this.bureauUnitsOnameField;
            }
            set {
                this.bureauUnitsOnameField = value;
                this.RaisePropertyChanged("bureauUnitsOname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=38)]
        public string dispatchLevel {
            get {
                return this.dispatchLevelField;
            }
            set {
                this.dispatchLevelField = value;
                this.RaisePropertyChanged("dispatchLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string dispatchLevelStr {
            get {
                return this.dispatchLevelStrField;
            }
            set {
                this.dispatchLevelStrField = value;
                this.RaisePropertyChanged("dispatchLevelStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public string runmanageOid {
            get {
                return this.runmanageOidField;
            }
            set {
                this.runmanageOidField = value;
                this.RaisePropertyChanged("runmanageOid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string runmanageOName {
            get {
                return this.runmanageONameField;
            }
            set {
                this.runmanageONameField = value;
                this.RaisePropertyChanged("runmanageOName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public string vindicateOid {
            get {
                return this.vindicateOidField;
            }
            set {
                this.vindicateOidField = value;
                this.RaisePropertyChanged("vindicateOid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public string vindicateOName {
            get {
                return this.vindicateONameField;
            }
            set {
                this.vindicateONameField = value;
                this.RaisePropertyChanged("vindicateOName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public string placeCode {
            get {
                return this.placeCodeField;
            }
            set {
                this.placeCodeField = value;
                this.RaisePropertyChanged("placeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public string flName {
            get {
                return this.flNameField;
            }
            set {
                this.flNameField = value;
                this.RaisePropertyChanged("flName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public string flCode {
            get {
                return this.flCodeField;
            }
            set {
                this.flCodeField = value;
                this.RaisePropertyChanged("flCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public string installCode {
            get {
                return this.installCodeField;
            }
            set {
                this.installCodeField = value;
                this.RaisePropertyChanged("installCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
                this.RaisePropertyChanged("remark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=49)]
        public string powerGridFlag {
            get {
                return this.powerGridFlagField;
            }
            set {
                this.powerGridFlagField = value;
                this.RaisePropertyChanged("powerGridFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=50)]
        public string powerGridFlagStr {
            get {
                return this.powerGridFlagStrField;
            }
            set {
                this.powerGridFlagStrField = value;
                this.RaisePropertyChanged("powerGridFlagStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=51)]
        public string ownerStationOid {
            get {
                return this.ownerStationOidField;
            }
            set {
                this.ownerStationOidField = value;
                this.RaisePropertyChanged("ownerStationOid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=52)]
        public string ownerStationOName {
            get {
                return this.ownerStationONameField;
            }
            set {
                this.ownerStationONameField = value;
                this.RaisePropertyChanged("ownerStationOName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=53)]
        public string countyCode {
            get {
                return this.countyCodeField;
            }
            set {
                this.countyCodeField = value;
                this.RaisePropertyChanged("countyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=54)]
        public string oldClassifyFullPath {
            get {
                return this.oldClassifyFullPathField;
            }
            set {
                this.oldClassifyFullPathField = value;
                this.RaisePropertyChanged("oldClassifyFullPath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=55)]
        public string oldAliasName {
            get {
                return this.oldAliasNameField;
            }
            set {
                this.oldAliasNameField = value;
                this.RaisePropertyChanged("oldAliasName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=56)]
        public string isLabel {
            get {
                return this.isLabelField;
            }
            set {
                this.isLabelField = value;
                this.RaisePropertyChanged("isLabel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=57)]
        public string isLabelStr {
            get {
                return this.isLabelStrField;
            }
            set {
                this.isLabelStrField = value;
                this.RaisePropertyChanged("isLabelStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=58)]
        public string isAssambly {
            get {
                return this.isAssamblyField;
            }
            set {
                this.isAssamblyField = value;
                this.RaisePropertyChanged("isAssambly");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=59)]
        public string isAssamblyStr {
            get {
                return this.isAssamblyStrField;
            }
            set {
                this.isAssamblyStrField = value;
                this.RaisePropertyChanged("isAssamblyStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=60)]
        public string isShareDevice {
            get {
                return this.isShareDeviceField;
            }
            set {
                this.isShareDeviceField = value;
                this.RaisePropertyChanged("isShareDevice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=61)]
        public string isShareDeviceStr {
            get {
                return this.isShareDeviceStrField;
            }
            set {
                this.isShareDeviceStrField = value;
                this.RaisePropertyChanged("isShareDeviceStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=62)]
        public string dataSource {
            get {
                return this.dataSourceField;
            }
            set {
                this.dataSourceField = value;
                this.RaisePropertyChanged("dataSource");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=63)]
        public string licensePlateNumber {
            get {
                return this.licensePlateNumberField;
            }
            set {
                this.licensePlateNumberField = value;
                this.RaisePropertyChanged("licensePlateNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=64)]
        public string vindicatorUnitOname {
            get {
                return this.vindicatorUnitOnameField;
            }
            set {
                this.vindicatorUnitOnameField = value;
                this.RaisePropertyChanged("vindicatorUnitOname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=65)]
        public string vindicatorUnitOid {
            get {
                return this.vindicatorUnitOidField;
            }
            set {
                this.vindicatorUnitOidField = value;
                this.RaisePropertyChanged("vindicatorUnitOid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=66)]
        public string capitalAssetsCode {
            get {
                return this.capitalAssetsCodeField;
            }
            set {
                this.capitalAssetsCodeField = value;
                this.RaisePropertyChanged("capitalAssetsCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=67)]
        public string installationLocation {
            get {
                return this.installationLocationField;
            }
            set {
                this.installationLocationField = value;
                this.RaisePropertyChanged("installationLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=68)]
        public string proprietorOwner {
            get {
                return this.proprietorOwnerField;
            }
            set {
                this.proprietorOwnerField = value;
                this.RaisePropertyChanged("proprietorOwner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=69)]
        public string proprietorOwnerStr {
            get {
                return this.proprietorOwnerStrField;
            }
            set {
                this.proprietorOwnerStrField = value;
                this.RaisePropertyChanged("proprietorOwnerStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=70)]
        public string useLife {
            get {
                return this.useLifeField;
            }
            set {
                this.useLifeField = value;
                this.RaisePropertyChanged("useLife");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=71)]
        public string deviceModelId {
            get {
                return this.deviceModelIdField;
            }
            set {
                this.deviceModelIdField = value;
                this.RaisePropertyChanged("deviceModelId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=72)]
        public string deviceId {
            get {
                return this.deviceIdField;
            }
            set {
                this.deviceIdField = value;
                this.RaisePropertyChanged("deviceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=73)]
        public string retireDateStr {
            get {
                return this.retireDateStrField;
            }
            set {
                this.retireDateStrField = value;
                this.RaisePropertyChanged("retireDateStr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=74)]
        public string functionLocationId {
            get {
                return this.functionLocationIdField;
            }
            set {
                this.functionLocationIdField = value;
                this.RaisePropertyChanged("functionLocationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=75)]
        public string classifyCode {
            get {
                return this.classifyCodeField;
            }
            set {
                this.classifyCodeField = value;
                this.RaisePropertyChanged("classifyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=76)]
        public string classifyFullPath {
            get {
                return this.classifyFullPathField;
            }
            set {
                this.classifyFullPathField = value;
                this.RaisePropertyChanged("classifyFullPath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=77)]
        public string nominalVoltage {
            get {
                return this.nominalVoltageField;
            }
            set {
                this.nominalVoltageField = value;
                this.RaisePropertyChanged("nominalVoltage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=78)]
        public string parentFLId {
            get {
                return this.parentFLIdField;
            }
            set {
                this.parentFLIdField = value;
                this.RaisePropertyChanged("parentFLId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=79)]
        public string parentFLName {
            get {
                return this.parentFLNameField;
            }
            set {
                this.parentFLNameField = value;
                this.RaisePropertyChanged("parentFLName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=80)]
        public string bayId {
            get {
                return this.bayIdField;
            }
            set {
                this.bayIdField = value;
                this.RaisePropertyChanged("bayId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=81)]
        public string bayName {
            get {
                return this.bayNameField;
            }
            set {
                this.bayNameField = value;
                this.RaisePropertyChanged("bayName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=82)]
        public string siteId {
            get {
                return this.siteIdField;
            }
            set {
                this.siteIdField = value;
                this.RaisePropertyChanged("siteId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=83)]
        public string siteName {
            get {
                return this.siteNameField;
            }
            set {
                this.siteNameField = value;
                this.RaisePropertyChanged("siteName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=84)]
        public string bureauName {
            get {
                return this.bureauNameField;
            }
            set {
                this.bureauNameField = value;
                this.RaisePropertyChanged("bureauName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=85)]
        public string fullPath {
            get {
                return this.fullPathField;
            }
            set {
                this.fullPathField = value;
                this.RaisePropertyChanged("fullPath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=86)]
        public string centerSubstationId {
            get {
                return this.centerSubstationIdField;
            }
            set {
                this.centerSubstationIdField = value;
                this.RaisePropertyChanged("centerSubstationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=87)]
        public string centerSubstationName {
            get {
                return this.centerSubstationNameField;
            }
            set {
                this.centerSubstationNameField = value;
                this.RaisePropertyChanged("centerSubstationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=88)]
        public string subsIdOfDisDevice {
            get {
                return this.subsIdOfDisDeviceField;
            }
            set {
                this.subsIdOfDisDeviceField = value;
                this.RaisePropertyChanged("subsIdOfDisDevice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=89)]
        public string subsNameOfDisDevice {
            get {
                return this.subsNameOfDisDeviceField;
            }
            set {
                this.subsNameOfDisDeviceField = value;
                this.RaisePropertyChanged("subsNameOfDisDevice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=90)]
        public string inventoryTaskNo {
            get {
                return this.inventoryTaskNoField;
            }
            set {
                this.inventoryTaskNoField = value;
                this.RaisePropertyChanged("inventoryTaskNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=91)]
        public string assetDeviceId {
            get {
                return this.assetDeviceIdField;
            }
            set {
                this.assetDeviceIdField = value;
                this.RaisePropertyChanged("assetDeviceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=92)]
        [System.Xml.Serialization.XmlArrayItemAttribute("lstTechParamItem", IsNullable=false)]
        public LstTechParamItem[] lstTechParamList {
            get {
                return this.lstTechParamListField;
            }
            set {
                this.lstTechParamListField = value;
                this.RaisePropertyChanged("lstTechParamList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.csg.cn")]
    public partial class QueryDeviceInfoByIdResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string replyCodeField;
        
        private DeviceGisDTO deviceGisDTOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string replyCode {
            get {
                return this.replyCodeField;
            }
            set {
                this.replyCodeField = value;
                this.RaisePropertyChanged("replyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public DeviceGisDTO deviceGisDTO {
            get {
                return this.deviceGisDTOField;
            }
            set {
                this.deviceGisDTOField = value;
                this.RaisePropertyChanged("deviceGisDTO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class queryDeviceInfoByIdRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.csg.cn", Order=0)]
        public PR.WizPlant.Integrate.Csgii.SBTZSOA.QueryDeviceInfoByIdRequest queryDeviceInfoByIdRequest;
        
        public queryDeviceInfoByIdRequest1() {
        }
        
        public queryDeviceInfoByIdRequest1(PR.WizPlant.Integrate.Csgii.SBTZSOA.QueryDeviceInfoByIdRequest queryDeviceInfoByIdRequest) {
            this.queryDeviceInfoByIdRequest = queryDeviceInfoByIdRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class queryDeviceInfoByIdResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soa.csg.cn", Order=0)]
        public PR.WizPlant.Integrate.Csgii.SBTZSOA.QueryDeviceInfoByIdResponse queryDeviceInfoByIdResponse;
        
        public queryDeviceInfoByIdResponse1() {
        }
        
        public queryDeviceInfoByIdResponse1(PR.WizPlant.Integrate.Csgii.SBTZSOA.QueryDeviceInfoByIdResponse queryDeviceInfoByIdResponse) {
            this.queryDeviceInfoByIdResponse = queryDeviceInfoByIdResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SOAServicePortChannel : PR.WizPlant.Integrate.Csgii.SBTZSOA.SOAServicePort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class queryDeviceInfoByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public queryDeviceInfoByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PR.WizPlant.Integrate.Csgii.SBTZSOA.QueryDeviceInfoByIdResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PR.WizPlant.Integrate.Csgii.SBTZSOA.QueryDeviceInfoByIdResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SOAServicePortClient : System.ServiceModel.ClientBase<PR.WizPlant.Integrate.Csgii.SBTZSOA.SOAServicePort>, PR.WizPlant.Integrate.Csgii.SBTZSOA.SOAServicePort {
        
        private BeginOperationDelegate onBeginqueryDeviceInfoByIdDelegate;
        
        private EndOperationDelegate onEndqueryDeviceInfoByIdDelegate;
        
        private System.Threading.SendOrPostCallback onqueryDeviceInfoByIdCompletedDelegate;
        
        public SOAServicePortClient() {
        }
        
        public SOAServicePortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SOAServicePortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SOAServicePortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SOAServicePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<queryDeviceInfoByIdCompletedEventArgs> queryDeviceInfoByIdCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PR.WizPlant.Integrate.Csgii.SBTZSOA.queryDeviceInfoByIdResponse1 PR.WizPlant.Integrate.Csgii.SBTZSOA.SOAServicePort.queryDeviceInfoById(PR.WizPlant.Integrate.Csgii.SBTZSOA.queryDeviceInfoByIdRequest1 request) {
            return base.Channel.queryDeviceInfoById(request);
        }
        
        public PR.WizPlant.Integrate.Csgii.SBTZSOA.QueryDeviceInfoByIdResponse queryDeviceInfoById(PR.WizPlant.Integrate.Csgii.SBTZSOA.QueryDeviceInfoByIdRequest queryDeviceInfoByIdRequest) {
            PR.WizPlant.Integrate.Csgii.SBTZSOA.queryDeviceInfoByIdRequest1 inValue = new PR.WizPlant.Integrate.Csgii.SBTZSOA.queryDeviceInfoByIdRequest1();
            inValue.queryDeviceInfoByIdRequest = queryDeviceInfoByIdRequest;
            PR.WizPlant.Integrate.Csgii.SBTZSOA.queryDeviceInfoByIdResponse1 retVal = ((PR.WizPlant.Integrate.Csgii.SBTZSOA.SOAServicePort)(this)).queryDeviceInfoById(inValue);
            return retVal.queryDeviceInfoByIdResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PR.WizPlant.Integrate.Csgii.SBTZSOA.SOAServicePort.BeginqueryDeviceInfoById(PR.WizPlant.Integrate.Csgii.SBTZSOA.queryDeviceInfoByIdRequest1 request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginqueryDeviceInfoById(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginqueryDeviceInfoById(PR.WizPlant.Integrate.Csgii.SBTZSOA.QueryDeviceInfoByIdRequest queryDeviceInfoByIdRequest, System.AsyncCallback callback, object asyncState) {
            PR.WizPlant.Integrate.Csgii.SBTZSOA.queryDeviceInfoByIdRequest1 inValue = new PR.WizPlant.Integrate.Csgii.SBTZSOA.queryDeviceInfoByIdRequest1();
            inValue.queryDeviceInfoByIdRequest = queryDeviceInfoByIdRequest;
            return ((PR.WizPlant.Integrate.Csgii.SBTZSOA.SOAServicePort)(this)).BeginqueryDeviceInfoById(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PR.WizPlant.Integrate.Csgii.SBTZSOA.queryDeviceInfoByIdResponse1 PR.WizPlant.Integrate.Csgii.SBTZSOA.SOAServicePort.EndqueryDeviceInfoById(System.IAsyncResult result) {
            return base.Channel.EndqueryDeviceInfoById(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public PR.WizPlant.Integrate.Csgii.SBTZSOA.QueryDeviceInfoByIdResponse EndqueryDeviceInfoById(System.IAsyncResult result) {
            PR.WizPlant.Integrate.Csgii.SBTZSOA.queryDeviceInfoByIdResponse1 retVal = ((PR.WizPlant.Integrate.Csgii.SBTZSOA.SOAServicePort)(this)).EndqueryDeviceInfoById(result);
            return retVal.queryDeviceInfoByIdResponse;
        }
        
        private System.IAsyncResult OnBeginqueryDeviceInfoById(object[] inValues, System.AsyncCallback callback, object asyncState) {
            PR.WizPlant.Integrate.Csgii.SBTZSOA.QueryDeviceInfoByIdRequest queryDeviceInfoByIdRequest = ((PR.WizPlant.Integrate.Csgii.SBTZSOA.QueryDeviceInfoByIdRequest)(inValues[0]));
            return this.BeginqueryDeviceInfoById(queryDeviceInfoByIdRequest, callback, asyncState);
        }
        
        private object[] OnEndqueryDeviceInfoById(System.IAsyncResult result) {
            PR.WizPlant.Integrate.Csgii.SBTZSOA.QueryDeviceInfoByIdResponse retVal = this.EndqueryDeviceInfoById(result);
            return new object[] {
                    retVal};
        }
        
        private void OnqueryDeviceInfoByIdCompleted(object state) {
            if ((this.queryDeviceInfoByIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.queryDeviceInfoByIdCompleted(this, new queryDeviceInfoByIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void queryDeviceInfoByIdAsync(PR.WizPlant.Integrate.Csgii.SBTZSOA.QueryDeviceInfoByIdRequest queryDeviceInfoByIdRequest) {
            this.queryDeviceInfoByIdAsync(queryDeviceInfoByIdRequest, null);
        }
        
        public void queryDeviceInfoByIdAsync(PR.WizPlant.Integrate.Csgii.SBTZSOA.QueryDeviceInfoByIdRequest queryDeviceInfoByIdRequest, object userState) {
            if ((this.onBeginqueryDeviceInfoByIdDelegate == null)) {
                this.onBeginqueryDeviceInfoByIdDelegate = new BeginOperationDelegate(this.OnBeginqueryDeviceInfoById);
            }
            if ((this.onEndqueryDeviceInfoByIdDelegate == null)) {
                this.onEndqueryDeviceInfoByIdDelegate = new EndOperationDelegate(this.OnEndqueryDeviceInfoById);
            }
            if ((this.onqueryDeviceInfoByIdCompletedDelegate == null)) {
                this.onqueryDeviceInfoByIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnqueryDeviceInfoByIdCompleted);
            }
            base.InvokeAsync(this.onBeginqueryDeviceInfoByIdDelegate, new object[] {
                        queryDeviceInfoByIdRequest}, this.onEndqueryDeviceInfoByIdDelegate, this.onqueryDeviceInfoByIdCompletedDelegate, userState);
        }
    }
}
