//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR.WizPlant.Integrate.Csgii.SBTZ {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="queryDeviceInfoByIdRequest", Namespace="http://sp.soa.csg.cn")]
    [System.SerializableAttribute()]
    public partial class queryDeviceInfoByIdRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string deviceIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string deviceId {
            get {
                return this.deviceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.deviceIdField, value) != true)) {
                    this.deviceIdField = value;
                    this.RaisePropertyChanged("deviceId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="queryDeviceInfoByIdResponse", Namespace="http://sp.soa.csg.cn")]
    [System.SerializableAttribute()]
    public partial class queryDeviceInfoByIdResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string replyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PR.WizPlant.Integrate.Csgii.SBTZ.deviceGisDTO deviceGisDTOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string replyCode {
            get {
                return this.replyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.replyCodeField, value) != true)) {
                    this.replyCodeField = value;
                    this.RaisePropertyChanged("replyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public PR.WizPlant.Integrate.Csgii.SBTZ.deviceGisDTO deviceGisDTO {
            get {
                return this.deviceGisDTOField;
            }
            set {
                if ((object.ReferenceEquals(this.deviceGisDTOField, value) != true)) {
                    this.deviceGisDTOField = value;
                    this.RaisePropertyChanged("deviceGisDTO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="deviceGisDTO", Namespace="http://sp.soa.csg.cn")]
    [System.SerializableAttribute()]
    public partial class deviceGisDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string deviceCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string deviceNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string classifyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string classifyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int isCapitalAssetsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string isCapitalAssetsStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string proprietorCompanyOnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string proprietorCompanyOidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string baseVoltageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string baseVoltageNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string voltagePageShowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int isVirtualDeviceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string isVirtualDeviceStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string measurementUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int amountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string manufacturerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string manufacturerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string latestManufacturerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vendorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vendorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string deviceModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string leaveFactoryNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string leaveFactoryDateStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int warrantyPeriodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string plantTransferDateStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int assetStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string assetStateStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusDateStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string runningCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double latitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double longitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string latitudeStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string longitudeStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int altitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int topographyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string topographyStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bureauUnitsOidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bureauUnitsOnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int dispatchLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dispatchLevelStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string runmanageOidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string runmanageONameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vindicateOidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vindicateONameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string placeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string flNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string flCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string installCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string remarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int powerGridFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string powerGridFlagStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ownerStationOidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ownerStationONameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string countyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string oldClassifyFullPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string oldAliasNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int isLabelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string isLabelStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int isAssamblyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string isAssamblyStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int isShareDeviceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string isShareDeviceStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dataSourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string licensePlateNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vindicatorUnitOnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vindicatorUnitOidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string capitalAssetsCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string installationLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int proprietorOwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string proprietorOwnerStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int useLifeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string deviceModelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string deviceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string retireDateStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string functionLocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string classifyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string classifyFullPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nominalVoltageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string parentFLIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string parentFLNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bayIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string siteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string siteNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bureauNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fullPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string centerSubstationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string centerSubstationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string subsIdOfDisDeviceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string subsNameOfDisDeviceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string inventoryTaskNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string assetDeviceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PR.WizPlant.Integrate.Csgii.SBTZ.deviceGisDTO.lstTechParamListType lstTechParamListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string deviceCode {
            get {
                return this.deviceCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.deviceCodeField, value) != true)) {
                    this.deviceCodeField = value;
                    this.RaisePropertyChanged("deviceCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string deviceName {
            get {
                return this.deviceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.deviceNameField, value) != true)) {
                    this.deviceNameField = value;
                    this.RaisePropertyChanged("deviceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string classifyId {
            get {
                return this.classifyIdField;
            }
            set {
                if ((object.ReferenceEquals(this.classifyIdField, value) != true)) {
                    this.classifyIdField = value;
                    this.RaisePropertyChanged("classifyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string classifyName {
            get {
                return this.classifyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.classifyNameField, value) != true)) {
                    this.classifyNameField = value;
                    this.RaisePropertyChanged("classifyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int isCapitalAssets {
            get {
                return this.isCapitalAssetsField;
            }
            set {
                if ((this.isCapitalAssetsField.Equals(value) != true)) {
                    this.isCapitalAssetsField = value;
                    this.RaisePropertyChanged("isCapitalAssets");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string isCapitalAssetsStr {
            get {
                return this.isCapitalAssetsStrField;
            }
            set {
                if ((object.ReferenceEquals(this.isCapitalAssetsStrField, value) != true)) {
                    this.isCapitalAssetsStrField = value;
                    this.RaisePropertyChanged("isCapitalAssetsStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string proprietorCompanyOname {
            get {
                return this.proprietorCompanyOnameField;
            }
            set {
                if ((object.ReferenceEquals(this.proprietorCompanyOnameField, value) != true)) {
                    this.proprietorCompanyOnameField = value;
                    this.RaisePropertyChanged("proprietorCompanyOname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string proprietorCompanyOid {
            get {
                return this.proprietorCompanyOidField;
            }
            set {
                if ((object.ReferenceEquals(this.proprietorCompanyOidField, value) != true)) {
                    this.proprietorCompanyOidField = value;
                    this.RaisePropertyChanged("proprietorCompanyOid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string baseVoltageId {
            get {
                return this.baseVoltageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.baseVoltageIdField, value) != true)) {
                    this.baseVoltageIdField = value;
                    this.RaisePropertyChanged("baseVoltageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string baseVoltageName {
            get {
                return this.baseVoltageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.baseVoltageNameField, value) != true)) {
                    this.baseVoltageNameField = value;
                    this.RaisePropertyChanged("baseVoltageName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string voltagePageShow {
            get {
                return this.voltagePageShowField;
            }
            set {
                if ((object.ReferenceEquals(this.voltagePageShowField, value) != true)) {
                    this.voltagePageShowField = value;
                    this.RaisePropertyChanged("voltagePageShow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public int isVirtualDevice {
            get {
                return this.isVirtualDeviceField;
            }
            set {
                if ((this.isVirtualDeviceField.Equals(value) != true)) {
                    this.isVirtualDeviceField = value;
                    this.RaisePropertyChanged("isVirtualDevice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string isVirtualDeviceStr {
            get {
                return this.isVirtualDeviceStrField;
            }
            set {
                if ((object.ReferenceEquals(this.isVirtualDeviceStrField, value) != true)) {
                    this.isVirtualDeviceStrField = value;
                    this.RaisePropertyChanged("isVirtualDeviceStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string measurementUnit {
            get {
                return this.measurementUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.measurementUnitField, value) != true)) {
                    this.measurementUnitField = value;
                    this.RaisePropertyChanged("measurementUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public int amount {
            get {
                return this.amountField;
            }
            set {
                if ((this.amountField.Equals(value) != true)) {
                    this.amountField = value;
                    this.RaisePropertyChanged("amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string manufacturer {
            get {
                return this.manufacturerField;
            }
            set {
                if ((object.ReferenceEquals(this.manufacturerField, value) != true)) {
                    this.manufacturerField = value;
                    this.RaisePropertyChanged("manufacturer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string manufacturerId {
            get {
                return this.manufacturerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.manufacturerIdField, value) != true)) {
                    this.manufacturerIdField = value;
                    this.RaisePropertyChanged("manufacturerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string latestManufacturer {
            get {
                return this.latestManufacturerField;
            }
            set {
                if ((object.ReferenceEquals(this.latestManufacturerField, value) != true)) {
                    this.latestManufacturerField = value;
                    this.RaisePropertyChanged("latestManufacturer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string vendor {
            get {
                return this.vendorField;
            }
            set {
                if ((object.ReferenceEquals(this.vendorField, value) != true)) {
                    this.vendorField = value;
                    this.RaisePropertyChanged("vendor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string vendorId {
            get {
                return this.vendorIdField;
            }
            set {
                if ((object.ReferenceEquals(this.vendorIdField, value) != true)) {
                    this.vendorIdField = value;
                    this.RaisePropertyChanged("vendorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string deviceModel {
            get {
                return this.deviceModelField;
            }
            set {
                if ((object.ReferenceEquals(this.deviceModelField, value) != true)) {
                    this.deviceModelField = value;
                    this.RaisePropertyChanged("deviceModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string leaveFactoryNo {
            get {
                return this.leaveFactoryNoField;
            }
            set {
                if ((object.ReferenceEquals(this.leaveFactoryNoField, value) != true)) {
                    this.leaveFactoryNoField = value;
                    this.RaisePropertyChanged("leaveFactoryNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string leaveFactoryDateStr {
            get {
                return this.leaveFactoryDateStrField;
            }
            set {
                if ((object.ReferenceEquals(this.leaveFactoryDateStrField, value) != true)) {
                    this.leaveFactoryDateStrField = value;
                    this.RaisePropertyChanged("leaveFactoryDateStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=23)]
        public int warrantyPeriod {
            get {
                return this.warrantyPeriodField;
            }
            set {
                if ((this.warrantyPeriodField.Equals(value) != true)) {
                    this.warrantyPeriodField = value;
                    this.RaisePropertyChanged("warrantyPeriod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string plantTransferDateStr {
            get {
                return this.plantTransferDateStrField;
            }
            set {
                if ((object.ReferenceEquals(this.plantTransferDateStrField, value) != true)) {
                    this.plantTransferDateStrField = value;
                    this.RaisePropertyChanged("plantTransferDateStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=25)]
        public int assetState {
            get {
                return this.assetStateField;
            }
            set {
                if ((this.assetStateField.Equals(value) != true)) {
                    this.assetStateField = value;
                    this.RaisePropertyChanged("assetState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string assetStateStr {
            get {
                return this.assetStateStrField;
            }
            set {
                if ((object.ReferenceEquals(this.assetStateStrField, value) != true)) {
                    this.assetStateStrField = value;
                    this.RaisePropertyChanged("assetStateStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string statusDateStr {
            get {
                return this.statusDateStrField;
            }
            set {
                if ((object.ReferenceEquals(this.statusDateStrField, value) != true)) {
                    this.statusDateStrField = value;
                    this.RaisePropertyChanged("statusDateStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string runningCode {
            get {
                return this.runningCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.runningCodeField, value) != true)) {
                    this.runningCodeField = value;
                    this.RaisePropertyChanged("runningCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=29)]
        public double latitude {
            get {
                return this.latitudeField;
            }
            set {
                if ((this.latitudeField.Equals(value) != true)) {
                    this.latitudeField = value;
                    this.RaisePropertyChanged("latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=30)]
        public double longitude {
            get {
                return this.longitudeField;
            }
            set {
                if ((this.longitudeField.Equals(value) != true)) {
                    this.longitudeField = value;
                    this.RaisePropertyChanged("longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=31)]
        public string latitudeStr {
            get {
                return this.latitudeStrField;
            }
            set {
                if ((object.ReferenceEquals(this.latitudeStrField, value) != true)) {
                    this.latitudeStrField = value;
                    this.RaisePropertyChanged("latitudeStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=32)]
        public string longitudeStr {
            get {
                return this.longitudeStrField;
            }
            set {
                if ((object.ReferenceEquals(this.longitudeStrField, value) != true)) {
                    this.longitudeStrField = value;
                    this.RaisePropertyChanged("longitudeStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=33)]
        public int altitude {
            get {
                return this.altitudeField;
            }
            set {
                if ((this.altitudeField.Equals(value) != true)) {
                    this.altitudeField = value;
                    this.RaisePropertyChanged("altitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=34)]
        public int topography {
            get {
                return this.topographyField;
            }
            set {
                if ((this.topographyField.Equals(value) != true)) {
                    this.topographyField = value;
                    this.RaisePropertyChanged("topography");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=35)]
        public string topographyStr {
            get {
                return this.topographyStrField;
            }
            set {
                if ((object.ReferenceEquals(this.topographyStrField, value) != true)) {
                    this.topographyStrField = value;
                    this.RaisePropertyChanged("topographyStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=36)]
        public string bureauUnitsOid {
            get {
                return this.bureauUnitsOidField;
            }
            set {
                if ((object.ReferenceEquals(this.bureauUnitsOidField, value) != true)) {
                    this.bureauUnitsOidField = value;
                    this.RaisePropertyChanged("bureauUnitsOid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=37)]
        public string bureauUnitsOname {
            get {
                return this.bureauUnitsOnameField;
            }
            set {
                if ((object.ReferenceEquals(this.bureauUnitsOnameField, value) != true)) {
                    this.bureauUnitsOnameField = value;
                    this.RaisePropertyChanged("bureauUnitsOname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=38)]
        public int dispatchLevel {
            get {
                return this.dispatchLevelField;
            }
            set {
                if ((this.dispatchLevelField.Equals(value) != true)) {
                    this.dispatchLevelField = value;
                    this.RaisePropertyChanged("dispatchLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=39)]
        public string dispatchLevelStr {
            get {
                return this.dispatchLevelStrField;
            }
            set {
                if ((object.ReferenceEquals(this.dispatchLevelStrField, value) != true)) {
                    this.dispatchLevelStrField = value;
                    this.RaisePropertyChanged("dispatchLevelStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=40)]
        public string runmanageOid {
            get {
                return this.runmanageOidField;
            }
            set {
                if ((object.ReferenceEquals(this.runmanageOidField, value) != true)) {
                    this.runmanageOidField = value;
                    this.RaisePropertyChanged("runmanageOid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=41)]
        public string runmanageOName {
            get {
                return this.runmanageONameField;
            }
            set {
                if ((object.ReferenceEquals(this.runmanageONameField, value) != true)) {
                    this.runmanageONameField = value;
                    this.RaisePropertyChanged("runmanageOName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=42)]
        public string vindicateOid {
            get {
                return this.vindicateOidField;
            }
            set {
                if ((object.ReferenceEquals(this.vindicateOidField, value) != true)) {
                    this.vindicateOidField = value;
                    this.RaisePropertyChanged("vindicateOid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=43)]
        public string vindicateOName {
            get {
                return this.vindicateONameField;
            }
            set {
                if ((object.ReferenceEquals(this.vindicateONameField, value) != true)) {
                    this.vindicateONameField = value;
                    this.RaisePropertyChanged("vindicateOName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=44)]
        public string placeCode {
            get {
                return this.placeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.placeCodeField, value) != true)) {
                    this.placeCodeField = value;
                    this.RaisePropertyChanged("placeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=45)]
        public string flName {
            get {
                return this.flNameField;
            }
            set {
                if ((object.ReferenceEquals(this.flNameField, value) != true)) {
                    this.flNameField = value;
                    this.RaisePropertyChanged("flName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=46)]
        public string flCode {
            get {
                return this.flCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.flCodeField, value) != true)) {
                    this.flCodeField = value;
                    this.RaisePropertyChanged("flCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=47)]
        public string installCode {
            get {
                return this.installCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.installCodeField, value) != true)) {
                    this.installCodeField = value;
                    this.RaisePropertyChanged("installCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=48)]
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                if ((object.ReferenceEquals(this.remarkField, value) != true)) {
                    this.remarkField = value;
                    this.RaisePropertyChanged("remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=49)]
        public int powerGridFlag {
            get {
                return this.powerGridFlagField;
            }
            set {
                if ((this.powerGridFlagField.Equals(value) != true)) {
                    this.powerGridFlagField = value;
                    this.RaisePropertyChanged("powerGridFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=50)]
        public string powerGridFlagStr {
            get {
                return this.powerGridFlagStrField;
            }
            set {
                if ((object.ReferenceEquals(this.powerGridFlagStrField, value) != true)) {
                    this.powerGridFlagStrField = value;
                    this.RaisePropertyChanged("powerGridFlagStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=51)]
        public string ownerStationOid {
            get {
                return this.ownerStationOidField;
            }
            set {
                if ((object.ReferenceEquals(this.ownerStationOidField, value) != true)) {
                    this.ownerStationOidField = value;
                    this.RaisePropertyChanged("ownerStationOid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=52)]
        public string ownerStationOName {
            get {
                return this.ownerStationONameField;
            }
            set {
                if ((object.ReferenceEquals(this.ownerStationONameField, value) != true)) {
                    this.ownerStationONameField = value;
                    this.RaisePropertyChanged("ownerStationOName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=53)]
        public string countyCode {
            get {
                return this.countyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.countyCodeField, value) != true)) {
                    this.countyCodeField = value;
                    this.RaisePropertyChanged("countyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=54)]
        public string oldClassifyFullPath {
            get {
                return this.oldClassifyFullPathField;
            }
            set {
                if ((object.ReferenceEquals(this.oldClassifyFullPathField, value) != true)) {
                    this.oldClassifyFullPathField = value;
                    this.RaisePropertyChanged("oldClassifyFullPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=55)]
        public string oldAliasName {
            get {
                return this.oldAliasNameField;
            }
            set {
                if ((object.ReferenceEquals(this.oldAliasNameField, value) != true)) {
                    this.oldAliasNameField = value;
                    this.RaisePropertyChanged("oldAliasName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=56)]
        public int isLabel {
            get {
                return this.isLabelField;
            }
            set {
                if ((this.isLabelField.Equals(value) != true)) {
                    this.isLabelField = value;
                    this.RaisePropertyChanged("isLabel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=57)]
        public string isLabelStr {
            get {
                return this.isLabelStrField;
            }
            set {
                if ((object.ReferenceEquals(this.isLabelStrField, value) != true)) {
                    this.isLabelStrField = value;
                    this.RaisePropertyChanged("isLabelStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=58)]
        public int isAssambly {
            get {
                return this.isAssamblyField;
            }
            set {
                if ((this.isAssamblyField.Equals(value) != true)) {
                    this.isAssamblyField = value;
                    this.RaisePropertyChanged("isAssambly");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=59)]
        public string isAssamblyStr {
            get {
                return this.isAssamblyStrField;
            }
            set {
                if ((object.ReferenceEquals(this.isAssamblyStrField, value) != true)) {
                    this.isAssamblyStrField = value;
                    this.RaisePropertyChanged("isAssamblyStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=60)]
        public int isShareDevice {
            get {
                return this.isShareDeviceField;
            }
            set {
                if ((this.isShareDeviceField.Equals(value) != true)) {
                    this.isShareDeviceField = value;
                    this.RaisePropertyChanged("isShareDevice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=61)]
        public string isShareDeviceStr {
            get {
                return this.isShareDeviceStrField;
            }
            set {
                if ((object.ReferenceEquals(this.isShareDeviceStrField, value) != true)) {
                    this.isShareDeviceStrField = value;
                    this.RaisePropertyChanged("isShareDeviceStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=62)]
        public string dataSource {
            get {
                return this.dataSourceField;
            }
            set {
                if ((object.ReferenceEquals(this.dataSourceField, value) != true)) {
                    this.dataSourceField = value;
                    this.RaisePropertyChanged("dataSource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=63)]
        public string licensePlateNumber {
            get {
                return this.licensePlateNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.licensePlateNumberField, value) != true)) {
                    this.licensePlateNumberField = value;
                    this.RaisePropertyChanged("licensePlateNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=64)]
        public string vindicatorUnitOname {
            get {
                return this.vindicatorUnitOnameField;
            }
            set {
                if ((object.ReferenceEquals(this.vindicatorUnitOnameField, value) != true)) {
                    this.vindicatorUnitOnameField = value;
                    this.RaisePropertyChanged("vindicatorUnitOname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=65)]
        public string vindicatorUnitOid {
            get {
                return this.vindicatorUnitOidField;
            }
            set {
                if ((object.ReferenceEquals(this.vindicatorUnitOidField, value) != true)) {
                    this.vindicatorUnitOidField = value;
                    this.RaisePropertyChanged("vindicatorUnitOid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=66)]
        public string capitalAssetsCode {
            get {
                return this.capitalAssetsCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.capitalAssetsCodeField, value) != true)) {
                    this.capitalAssetsCodeField = value;
                    this.RaisePropertyChanged("capitalAssetsCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=67)]
        public string installationLocation {
            get {
                return this.installationLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.installationLocationField, value) != true)) {
                    this.installationLocationField = value;
                    this.RaisePropertyChanged("installationLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=68)]
        public int proprietorOwner {
            get {
                return this.proprietorOwnerField;
            }
            set {
                if ((this.proprietorOwnerField.Equals(value) != true)) {
                    this.proprietorOwnerField = value;
                    this.RaisePropertyChanged("proprietorOwner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=69)]
        public string proprietorOwnerStr {
            get {
                return this.proprietorOwnerStrField;
            }
            set {
                if ((object.ReferenceEquals(this.proprietorOwnerStrField, value) != true)) {
                    this.proprietorOwnerStrField = value;
                    this.RaisePropertyChanged("proprietorOwnerStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=70)]
        public int useLife {
            get {
                return this.useLifeField;
            }
            set {
                if ((this.useLifeField.Equals(value) != true)) {
                    this.useLifeField = value;
                    this.RaisePropertyChanged("useLife");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=71)]
        public string deviceModelId {
            get {
                return this.deviceModelIdField;
            }
            set {
                if ((object.ReferenceEquals(this.deviceModelIdField, value) != true)) {
                    this.deviceModelIdField = value;
                    this.RaisePropertyChanged("deviceModelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=72)]
        public string deviceId {
            get {
                return this.deviceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.deviceIdField, value) != true)) {
                    this.deviceIdField = value;
                    this.RaisePropertyChanged("deviceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=73)]
        public string retireDateStr {
            get {
                return this.retireDateStrField;
            }
            set {
                if ((object.ReferenceEquals(this.retireDateStrField, value) != true)) {
                    this.retireDateStrField = value;
                    this.RaisePropertyChanged("retireDateStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=74)]
        public string functionLocationId {
            get {
                return this.functionLocationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.functionLocationIdField, value) != true)) {
                    this.functionLocationIdField = value;
                    this.RaisePropertyChanged("functionLocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=75)]
        public string classifyCode {
            get {
                return this.classifyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.classifyCodeField, value) != true)) {
                    this.classifyCodeField = value;
                    this.RaisePropertyChanged("classifyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=76)]
        public string classifyFullPath {
            get {
                return this.classifyFullPathField;
            }
            set {
                if ((object.ReferenceEquals(this.classifyFullPathField, value) != true)) {
                    this.classifyFullPathField = value;
                    this.RaisePropertyChanged("classifyFullPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=77)]
        public int nominalVoltage {
            get {
                return this.nominalVoltageField;
            }
            set {
                if ((this.nominalVoltageField.Equals(value) != true)) {
                    this.nominalVoltageField = value;
                    this.RaisePropertyChanged("nominalVoltage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=78)]
        public string parentFLId {
            get {
                return this.parentFLIdField;
            }
            set {
                if ((object.ReferenceEquals(this.parentFLIdField, value) != true)) {
                    this.parentFLIdField = value;
                    this.RaisePropertyChanged("parentFLId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=79)]
        public string parentFLName {
            get {
                return this.parentFLNameField;
            }
            set {
                if ((object.ReferenceEquals(this.parentFLNameField, value) != true)) {
                    this.parentFLNameField = value;
                    this.RaisePropertyChanged("parentFLName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=80)]
        public string bayId {
            get {
                return this.bayIdField;
            }
            set {
                if ((object.ReferenceEquals(this.bayIdField, value) != true)) {
                    this.bayIdField = value;
                    this.RaisePropertyChanged("bayId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=81)]
        public string bayName {
            get {
                return this.bayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.bayNameField, value) != true)) {
                    this.bayNameField = value;
                    this.RaisePropertyChanged("bayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=82)]
        public string siteId {
            get {
                return this.siteIdField;
            }
            set {
                if ((object.ReferenceEquals(this.siteIdField, value) != true)) {
                    this.siteIdField = value;
                    this.RaisePropertyChanged("siteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=83)]
        public string siteName {
            get {
                return this.siteNameField;
            }
            set {
                if ((object.ReferenceEquals(this.siteNameField, value) != true)) {
                    this.siteNameField = value;
                    this.RaisePropertyChanged("siteName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=84)]
        public string bureauName {
            get {
                return this.bureauNameField;
            }
            set {
                if ((object.ReferenceEquals(this.bureauNameField, value) != true)) {
                    this.bureauNameField = value;
                    this.RaisePropertyChanged("bureauName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=85)]
        public string fullPath {
            get {
                return this.fullPathField;
            }
            set {
                if ((object.ReferenceEquals(this.fullPathField, value) != true)) {
                    this.fullPathField = value;
                    this.RaisePropertyChanged("fullPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=86)]
        public string centerSubstationId {
            get {
                return this.centerSubstationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.centerSubstationIdField, value) != true)) {
                    this.centerSubstationIdField = value;
                    this.RaisePropertyChanged("centerSubstationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=87)]
        public string centerSubstationName {
            get {
                return this.centerSubstationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.centerSubstationNameField, value) != true)) {
                    this.centerSubstationNameField = value;
                    this.RaisePropertyChanged("centerSubstationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=88)]
        public string subsIdOfDisDevice {
            get {
                return this.subsIdOfDisDeviceField;
            }
            set {
                if ((object.ReferenceEquals(this.subsIdOfDisDeviceField, value) != true)) {
                    this.subsIdOfDisDeviceField = value;
                    this.RaisePropertyChanged("subsIdOfDisDevice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=89)]
        public string subsNameOfDisDevice {
            get {
                return this.subsNameOfDisDeviceField;
            }
            set {
                if ((object.ReferenceEquals(this.subsNameOfDisDeviceField, value) != true)) {
                    this.subsNameOfDisDeviceField = value;
                    this.RaisePropertyChanged("subsNameOfDisDevice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=90)]
        public string inventoryTaskNo {
            get {
                return this.inventoryTaskNoField;
            }
            set {
                if ((object.ReferenceEquals(this.inventoryTaskNoField, value) != true)) {
                    this.inventoryTaskNoField = value;
                    this.RaisePropertyChanged("inventoryTaskNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=91)]
        public string assetDeviceId {
            get {
                return this.assetDeviceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.assetDeviceIdField, value) != true)) {
                    this.assetDeviceIdField = value;
                    this.RaisePropertyChanged("assetDeviceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=92)]
        public PR.WizPlant.Integrate.Csgii.SBTZ.deviceGisDTO.lstTechParamListType lstTechParamList {
            get {
                return this.lstTechParamListField;
            }
            set {
                if ((object.ReferenceEquals(this.lstTechParamListField, value) != true)) {
                    this.lstTechParamListField = value;
                    this.RaisePropertyChanged("lstTechParamList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.CollectionDataContractAttribute(Name="deviceGisDTO.lstTechParamListType", Namespace="http://sp.soa.csg.cn", ItemName="lstTechParamItem")]
        [System.SerializableAttribute()]
        public class lstTechParamListType : System.Collections.Generic.List<PR.WizPlant.Integrate.Csgii.SBTZ.techParamValueGisDTO> {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="techParamValueGisDTO", Namespace="http://sp.soa.csg.cn")]
    [System.SerializableAttribute()]
    public partial class techParamValueGisDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string classifyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string classifyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string techParamIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string columnNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string techParamNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string techParamValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string unitsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int isMandatoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int isShowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sortNoField;
        
        private int dataTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int isVendorFillField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string classifyId {
            get {
                return this.classifyIdField;
            }
            set {
                if ((object.ReferenceEquals(this.classifyIdField, value) != true)) {
                    this.classifyIdField = value;
                    this.RaisePropertyChanged("classifyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string classifyName {
            get {
                return this.classifyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.classifyNameField, value) != true)) {
                    this.classifyNameField = value;
                    this.RaisePropertyChanged("classifyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string techParamId {
            get {
                return this.techParamIdField;
            }
            set {
                if ((object.ReferenceEquals(this.techParamIdField, value) != true)) {
                    this.techParamIdField = value;
                    this.RaisePropertyChanged("techParamId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string columnName {
            get {
                return this.columnNameField;
            }
            set {
                if ((object.ReferenceEquals(this.columnNameField, value) != true)) {
                    this.columnNameField = value;
                    this.RaisePropertyChanged("columnName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string techParamName {
            get {
                return this.techParamNameField;
            }
            set {
                if ((object.ReferenceEquals(this.techParamNameField, value) != true)) {
                    this.techParamNameField = value;
                    this.RaisePropertyChanged("techParamName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string techParamValue {
            get {
                return this.techParamValueField;
            }
            set {
                if ((object.ReferenceEquals(this.techParamValueField, value) != true)) {
                    this.techParamValueField = value;
                    this.RaisePropertyChanged("techParamValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string units {
            get {
                return this.unitsField;
            }
            set {
                if ((object.ReferenceEquals(this.unitsField, value) != true)) {
                    this.unitsField = value;
                    this.RaisePropertyChanged("units");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int isMandatory {
            get {
                return this.isMandatoryField;
            }
            set {
                if ((this.isMandatoryField.Equals(value) != true)) {
                    this.isMandatoryField = value;
                    this.RaisePropertyChanged("isMandatory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int isShow {
            get {
                return this.isShowField;
            }
            set {
                if ((this.isShowField.Equals(value) != true)) {
                    this.isShowField = value;
                    this.RaisePropertyChanged("isShow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public int sortNo {
            get {
                return this.sortNoField;
            }
            set {
                if ((this.sortNoField.Equals(value) != true)) {
                    this.sortNoField = value;
                    this.RaisePropertyChanged("sortNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int dataType {
            get {
                return this.dataTypeField;
            }
            set {
                if ((this.dataTypeField.Equals(value) != true)) {
                    this.dataTypeField = value;
                    this.RaisePropertyChanged("dataType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public int isVendorFill {
            get {
                return this.isVendorFillField;
            }
            set {
                if ((this.isVendorFillField.Equals(value) != true)) {
                    this.isVendorFillField = value;
                    this.RaisePropertyChanged("isVendorFill");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sp.soa.csg.cn", ConfigurationName="SBTZ.IDeviceInfoForGisImpl_queryDeviceInfoById")]
    public interface IDeviceInfoForGisImpl_queryDeviceInfoById {
        
        // CODEGEN: 操作 queryDeviceInfoById 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        PR.WizPlant.Integrate.Csgii.SBTZ.queryDeviceInfoByIdResponse1 queryDeviceInfoById(PR.WizPlant.Integrate.Csgii.SBTZ.queryDeviceInfoByIdRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult BeginqueryDeviceInfoById(PR.WizPlant.Integrate.Csgii.SBTZ.queryDeviceInfoByIdRequest1 request, System.AsyncCallback callback, object asyncState);
        
        PR.WizPlant.Integrate.Csgii.SBTZ.queryDeviceInfoByIdResponse1 EndqueryDeviceInfoById(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class queryDeviceInfoByIdRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sp.soa.csg.cn", Order=0)]
        public PR.WizPlant.Integrate.Csgii.SBTZ.queryDeviceInfoByIdRequest queryDeviceInfoByIdRequest;
        
        public queryDeviceInfoByIdRequest1() {
        }
        
        public queryDeviceInfoByIdRequest1(PR.WizPlant.Integrate.Csgii.SBTZ.queryDeviceInfoByIdRequest queryDeviceInfoByIdRequest) {
            this.queryDeviceInfoByIdRequest = queryDeviceInfoByIdRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class queryDeviceInfoByIdResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sp.soa.csg.cn", Order=0)]
        public PR.WizPlant.Integrate.Csgii.SBTZ.queryDeviceInfoByIdResponse queryDeviceInfoByIdResponse;
        
        public queryDeviceInfoByIdResponse1() {
        }
        
        public queryDeviceInfoByIdResponse1(PR.WizPlant.Integrate.Csgii.SBTZ.queryDeviceInfoByIdResponse queryDeviceInfoByIdResponse) {
            this.queryDeviceInfoByIdResponse = queryDeviceInfoByIdResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDeviceInfoForGisImpl_queryDeviceInfoByIdChannel : PR.WizPlant.Integrate.Csgii.SBTZ.IDeviceInfoForGisImpl_queryDeviceInfoById, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class queryDeviceInfoByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public queryDeviceInfoByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PR.WizPlant.Integrate.Csgii.SBTZ.queryDeviceInfoByIdResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PR.WizPlant.Integrate.Csgii.SBTZ.queryDeviceInfoByIdResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeviceInfoForGisImpl_queryDeviceInfoByIdClient : System.ServiceModel.ClientBase<PR.WizPlant.Integrate.Csgii.SBTZ.IDeviceInfoForGisImpl_queryDeviceInfoById>, PR.WizPlant.Integrate.Csgii.SBTZ.IDeviceInfoForGisImpl_queryDeviceInfoById {
        
        private BeginOperationDelegate onBeginqueryDeviceInfoByIdDelegate;
        
        private EndOperationDelegate onEndqueryDeviceInfoByIdDelegate;
        
        private System.Threading.SendOrPostCallback onqueryDeviceInfoByIdCompletedDelegate;
        
        public DeviceInfoForGisImpl_queryDeviceInfoByIdClient() {
        }
        
        public DeviceInfoForGisImpl_queryDeviceInfoByIdClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeviceInfoForGisImpl_queryDeviceInfoByIdClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeviceInfoForGisImpl_queryDeviceInfoByIdClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeviceInfoForGisImpl_queryDeviceInfoByIdClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<queryDeviceInfoByIdCompletedEventArgs> queryDeviceInfoByIdCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PR.WizPlant.Integrate.Csgii.SBTZ.queryDeviceInfoByIdResponse1 PR.WizPlant.Integrate.Csgii.SBTZ.IDeviceInfoForGisImpl_queryDeviceInfoById.queryDeviceInfoById(PR.WizPlant.Integrate.Csgii.SBTZ.queryDeviceInfoByIdRequest1 request) {
            return base.Channel.queryDeviceInfoById(request);
        }
        
        public PR.WizPlant.Integrate.Csgii.SBTZ.queryDeviceInfoByIdResponse queryDeviceInfoById(PR.WizPlant.Integrate.Csgii.SBTZ.queryDeviceInfoByIdRequest queryDeviceInfoByIdRequest) {
            PR.WizPlant.Integrate.Csgii.SBTZ.queryDeviceInfoByIdRequest1 inValue = new PR.WizPlant.Integrate.Csgii.SBTZ.queryDeviceInfoByIdRequest1();
            inValue.queryDeviceInfoByIdRequest = queryDeviceInfoByIdRequest;
            PR.WizPlant.Integrate.Csgii.SBTZ.queryDeviceInfoByIdResponse1 retVal = ((PR.WizPlant.Integrate.Csgii.SBTZ.IDeviceInfoForGisImpl_queryDeviceInfoById)(this)).queryDeviceInfoById(inValue);
            return retVal.queryDeviceInfoByIdResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PR.WizPlant.Integrate.Csgii.SBTZ.IDeviceInfoForGisImpl_queryDeviceInfoById.BeginqueryDeviceInfoById(PR.WizPlant.Integrate.Csgii.SBTZ.queryDeviceInfoByIdRequest1 request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginqueryDeviceInfoById(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginqueryDeviceInfoById(PR.WizPlant.Integrate.Csgii.SBTZ.queryDeviceInfoByIdRequest queryDeviceInfoByIdRequest, System.AsyncCallback callback, object asyncState) {
            PR.WizPlant.Integrate.Csgii.SBTZ.queryDeviceInfoByIdRequest1 inValue = new PR.WizPlant.Integrate.Csgii.SBTZ.queryDeviceInfoByIdRequest1();
            inValue.queryDeviceInfoByIdRequest = queryDeviceInfoByIdRequest;
            return ((PR.WizPlant.Integrate.Csgii.SBTZ.IDeviceInfoForGisImpl_queryDeviceInfoById)(this)).BeginqueryDeviceInfoById(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PR.WizPlant.Integrate.Csgii.SBTZ.queryDeviceInfoByIdResponse1 PR.WizPlant.Integrate.Csgii.SBTZ.IDeviceInfoForGisImpl_queryDeviceInfoById.EndqueryDeviceInfoById(System.IAsyncResult result) {
            return base.Channel.EndqueryDeviceInfoById(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public PR.WizPlant.Integrate.Csgii.SBTZ.queryDeviceInfoByIdResponse EndqueryDeviceInfoById(System.IAsyncResult result) {
            PR.WizPlant.Integrate.Csgii.SBTZ.queryDeviceInfoByIdResponse1 retVal = ((PR.WizPlant.Integrate.Csgii.SBTZ.IDeviceInfoForGisImpl_queryDeviceInfoById)(this)).EndqueryDeviceInfoById(result);
            return retVal.queryDeviceInfoByIdResponse;
        }
        
        private System.IAsyncResult OnBeginqueryDeviceInfoById(object[] inValues, System.AsyncCallback callback, object asyncState) {
            PR.WizPlant.Integrate.Csgii.SBTZ.queryDeviceInfoByIdRequest queryDeviceInfoByIdRequest = ((PR.WizPlant.Integrate.Csgii.SBTZ.queryDeviceInfoByIdRequest)(inValues[0]));
            return this.BeginqueryDeviceInfoById(queryDeviceInfoByIdRequest, callback, asyncState);
        }
        
        private object[] OnEndqueryDeviceInfoById(System.IAsyncResult result) {
            PR.WizPlant.Integrate.Csgii.SBTZ.queryDeviceInfoByIdResponse retVal = this.EndqueryDeviceInfoById(result);
            return new object[] {
                    retVal};
        }
        
        private void OnqueryDeviceInfoByIdCompleted(object state) {
            if ((this.queryDeviceInfoByIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.queryDeviceInfoByIdCompleted(this, new queryDeviceInfoByIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void queryDeviceInfoByIdAsync(PR.WizPlant.Integrate.Csgii.SBTZ.queryDeviceInfoByIdRequest queryDeviceInfoByIdRequest) {
            this.queryDeviceInfoByIdAsync(queryDeviceInfoByIdRequest, null);
        }
        
        public void queryDeviceInfoByIdAsync(PR.WizPlant.Integrate.Csgii.SBTZ.queryDeviceInfoByIdRequest queryDeviceInfoByIdRequest, object userState) {
            if ((this.onBeginqueryDeviceInfoByIdDelegate == null)) {
                this.onBeginqueryDeviceInfoByIdDelegate = new BeginOperationDelegate(this.OnBeginqueryDeviceInfoById);
            }
            if ((this.onEndqueryDeviceInfoByIdDelegate == null)) {
                this.onEndqueryDeviceInfoByIdDelegate = new EndOperationDelegate(this.OnEndqueryDeviceInfoById);
            }
            if ((this.onqueryDeviceInfoByIdCompletedDelegate == null)) {
                this.onqueryDeviceInfoByIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnqueryDeviceInfoByIdCompleted);
            }
            base.InvokeAsync(this.onBeginqueryDeviceInfoByIdDelegate, new object[] {
                        queryDeviceInfoByIdRequest}, this.onEndqueryDeviceInfoByIdDelegate, this.onqueryDeviceInfoByIdCompletedDelegate, userState);
        }
    }
}
